/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package papeleria;

import Metodos.Conexion;
import Metodos.TablaProductos;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Rodrigo
 */
public class Ventas extends javax.swing.JFrame {

    DefaultComboBoxModel<String> modelCombo = new DefaultComboBoxModel<>();
    DefaultTableModel modelTabla;
    Conexion conexion = new Conexion();

    Map<Integer, TablaProductos> productos = new HashMap<Integer, TablaProductos>();
    Map<String, Integer> mapa = new HashMap<>(0);
    Map<Integer, Integer> mapaCantidad = new HashMap<>();

    /**
     * Creates new form Vender
     */
    public Ventas() {
        initComponents();
        iniciarCombobox();
        iniciarTabla();
        this.setLocationRelativeTo(null);
        /*
        for (Map.Entry<Integer, TablaProductos> entry : productos.entrySet()) {
            System.out.println(entry.getValue().getNombre());
        }*/
        btnRealizarCompra.setVisible(false);
    }

    private void iniciarCombobox() {
        String Nombre = "";
        double PrecioU = 0.0;
        int id = 0, Stock = 0;

        ResultSet rs = null;
        rs = conexion.TablaInventario(rs, true);

        try {
            while (rs.next()) {
                id = rs.getInt("id");
                Nombre = rs.getString("nombre");
                PrecioU = rs.getDouble("precio_unitario");
                Stock = rs.getInt("cantidad_stock");

                mapa.put(rs.getString("nombre"), rs.getInt("id"));
                productos.put(id, new TablaProductos(id, Stock, PrecioU, Nombre));

                modelCombo.addElement(rs.getString("nombre"));
            }
        } catch (Exception err) {
            System.out.println(err);
        }

        AutoCompleteDecorator.decorate(comboProducto);
    }

    private void iniciarTabla() {
        modelTabla = new DefaultTableModel();
        tablaCarrito.setModel(modelTabla);

        modelTabla.addColumn("id");
        modelTabla.addColumn("Nombre");
        modelTabla.addColumn("Precio/U");
        modelTabla.addColumn("Cantidad");
        modelTabla.addColumn("Precio/T");

        TableColumnModel columnModel = tablaCarrito.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(20);
        columnModel.getColumn(0).setMaxWidth(50);

        //modelTabla.addRow(new Object[]{});
    }

    private void agregarProducto(String nombre, int cantidad) {
        int id = mapa.get(nombre);
        TablaProductos tabla = productos.get(id);

        for (int i = 0; i < modelTabla.getRowCount(); i++) {
            if ((Integer) modelTabla.getValueAt(i, 0) == id) {
                modelTabla.removeRow(i);
            }
        }

        mapaCantidad.put(id, ((mapaCantidad.get(id)) != null ? mapaCantidad.get(id) + cantidad : cantidad));
        modelTabla.addRow(new Object[]{tabla.getId(), tabla.getNombre(), "$" + tabla.getPrecio(), mapaCantidad.get(id), "$" + (tabla.getPrecio() * mapaCantidad.get(id))});
        double precioTotal = 0;
        for (int i = 0; i < modelTabla.getRowCount(); i++) {
            String s = modelTabla.getValueAt(i, 4).toString().substring(1);
            precioTotal += Double.parseDouble(s);
        }
        txtPrecioTotal.setText("$" + precioTotal);
    }

    private void realizarCompra() {
        int rows = modelTabla.getRowCount();
        for (int i = 0; i < rows; i++) {
            int id = (Integer) modelTabla.getValueAt(0, 0);
            int cantidad = (Integer) modelTabla.getValueAt(0, 3);
            conexion.comprar(productos.get(id), cantidad);
            modelTabla.removeRow(0);
        }
        mapaCantidad.clear();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinnerCantidad = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtPrecioTotal = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnRealizarCompra = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboProducto.setBackground(new java.awt.Color(153, 153, 0));
        comboProducto.setEditable(true);
        comboProducto.setModel(modelCombo);
        comboProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(235, 198, 83), 3, true));
        comboProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProductoItemStateChanged(evt);
            }
        });
        getContentPane().add(comboProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 220, -1));

        tablaCarrito.setBackground(new java.awt.Color(235, 198, 83));
        tablaCarrito.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tablaCarrito.setForeground(new java.awt.Color(0, 0, 0));
        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Pieza/U", "Pieza/T"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaCarrito.setCellSelectionEnabled(true);
        tablaCarrito.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tablaCarrito);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 580, 170));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Precio Total:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 100, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cantidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Producto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        spinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spinnerCantidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(235, 198, 83), 2, true));
        getContentPane().add(spinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 50, 30));

        jButton1.setBackground(new java.awt.Color(235, 198, 83));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Historial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 100, -1));

        btnAgregar.setBackground(new java.awt.Color(235, 198, 83));
        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 90, -1));

        txtPrecioTotal.setEditable(false);
        txtPrecioTotal.setBackground(new java.awt.Color(235, 198, 83));
        txtPrecioTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txtPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 110, 20));

        btnVolver.setBackground(new java.awt.Color(235, 198, 83));
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Menú");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(235, 198, 83)));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, 30));

        btnRealizarCompra.setBackground(new java.awt.Color(235, 198, 83));
        btnRealizarCompra.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnRealizarCompra.setForeground(new java.awt.Color(0, 0, 0));
        btnRealizarCompra.setText("Realizar compra");
        btnRealizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 160, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inventario2.PNG"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Historial historial = new Historial();
        historial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarProducto(comboProducto.getSelectedItem().toString(), (Integer) spinnerCantidad.getValue());
        spinnerCantidad.setValue(1);
        btnRealizarCompra.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Menu abrir = new Menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void comboProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProductoItemStateChanged
    }//GEN-LAST:event_comboProductoItemStateChanged

    private void btnRealizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarCompraActionPerformed
        //int i = JOptionPane.showConfirmDialog(this, "Quieres?");
        //System.out.println(i);
        switch (JOptionPane.showConfirmDialog(this, "Desea realizar la compra por " + txtPrecioTotal.getText() + "?")) {
            case 0:
                realizarCompra();
                btnRealizarCompra.setVisible(false);
                break;
            case 1:
                System.out.println("no ok");
                break;
        }
    }//GEN-LAST:event_btnRealizarCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRealizarCompra;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerCantidad;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTextField txtPrecioTotal;
    // End of variables declaration//GEN-END:variables

}
